apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma-tls
  namespace: uptime-kuma
spec:
  secretName: uptime-kuma-tls
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - uptime.local
